# Generated by Django 3.0.8 on 2020-08-06 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='internship',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='hr',
            name='internship',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hr',
            name='placement',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='company',
            name='placement',
            field=models.BooleanField(default=False),
        ),
    ]
