# Generated by Django 3.0.8 on 2020-08-07 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_auto_20200806_1551'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='hr',
            options={'verbose_name': 'HR', 'verbose_name_plural': 'HRs'},
        ),
        migrations.AlterModelOptions(
            name='remark',
            options={'verbose_name': 'Remark', 'verbose_name_plural': 'Remarks'},
        ),
    ]
