# Generated by Django 3.0.8 on 2020-08-09 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='remark',
            name='placement',
            field=models.BooleanField(default=False),
        ),
    ]
