# Generated by Django 3.1 on 2020-08-27 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='response',
            field=models.JSONField(blank=True, editable=False, null=True),
        ),
    ]
