# Generated by Django 3.0.8 on 2020-08-19 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_auto_20200819_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='year',
            field=models.IntegerField(blank=True, editable=False),
        ),
    ]
