# Generated by Django 3.1.2 on 2021-01-17 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_todo1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='year',
            field=models.IntegerField(blank=True, default=2021),
        ),
    ]
