# Generated by Django 3.0.8 on 2020-08-12 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_remark_placement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remark',
            name='company',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='remarks', to='diary.Company'),
        ),
        migrations.AlterField(
            model_name='remark',
            name='placement',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='remark',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remarks', to=settings.AUTH_USER_MODEL),
        ),
    ]
