# Generated by Django 3.0.8 on 2020-08-20 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_auto_20200819_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='datetime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='company',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, editable=False),
        ),
    ]
