# Generated by Django 3.1.2 on 2021-01-17 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_auto_20210117_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='author',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='todo1',
            name='author',
            field=models.CharField(default='', max_length=100),
        ),
    ]
