# Generated by Django 3.1.2 on 2021-01-17 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0004_auto_20210117_1014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='author',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='todo1',
            old_name='author',
            new_name='username',
        ),
    ]
