# Generated by Django 3.0.8 on 2020-08-20 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0004_auto_20200820_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='year',
            field=models.IntegerField(blank=True),
        ),
    ]
