# Generated by Django 3.0.8 on 2020-08-20 12:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0005_auto_20200820_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='company',
            name='year',
            field=models.IntegerField(blank=True, default=2020),
        ),
    ]
