# Generated by Django 3.1.2 on 2021-01-26 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0006_auto_20210123_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo1',
            name='username',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks1', to=settings.AUTH_USER_MODEL),
        ),
    ]
