# Generated by Django 3.0.8 on 2020-08-20 14:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0006_auto_20200820_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remark',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
