# Generated by Django 3.0.8 on 2020-08-21 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0007_auto_20200820_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='logo',
        ),
    ]
