# Generated by Django 3.1.2 on 2021-04-02 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0009_activities_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='company_name',
            field=models.TextField(default=''),
        ),
    ]
