# Generated by Django 3.1.2 on 2021-04-05 18:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0011_company_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='hr',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr', to=settings.AUTH_USER_MODEL),
        ),
    ]
